# Generated by Django 4.2.8 on 2023-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dbid',
            field=models.TextField(default='0'),
        ),
    ]
